input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] =~ /gateway/ {
    json {
      source => "message"
      skip_on_invalid_json => true
    }

    date {
      match => ["time", "ISO8601"]
      target => "@timestamp"
    }

    mutate {
      rename => {
        "level" => "log_level"
        "msg"   => "log_message"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "gateway-service-%{+YYYY.MM.dd}"
  }
}