input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] =~ /analytics-service/ {
    json {
      source => "message"
      target => "log"
    }

    if [log][level] {
      mutate {
        rename => { "[log][level]" => "level" }
        rename => { "[log][msg]"   => "msg" }
        rename => { "[log][time]"  => "log_time" }
      }
    }

    mutate {
      add_field => { "service" => "analytics-service" }
      remove_field => ["message", "log"]
    }

    date {
      match => ["log_time", "ISO8601"]
      target => "@timestamp"
      remove_field => ["log_time"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "analytics-service-%{+YYYY.MM.dd}"
  }
}